import { useEffect, useMemo, useRef, useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import QRCode from 'qrcode';
import jsQR from 'jsqr';
import { DeviceType, Frame, TransferMeta, frameText, makeTransfer, parseFrame, reconstruct, sha256 } from './protocol';
import { getHistory, HistoryItem, saveHistory } from './storage';

type Mode = 'home' | 'send' | 'receive';
const spring = { type: 'spring', stiffness: 420, damping: 28 } as const;
const bytes = (n:number) => { if(n < 1024) return `${n} B`; const units=['KB','MB','GB','TB']; let i=-1; do { n/=1024; i++; } while(n>=1024 && i<units.length-1); return `${n.toFixed(n>=100?0:1)} ${units[i]}`; };

function Button({ children, onClick, primary=false, disabled=false }: { children:React.ReactNode; onClick?:()=>void; primary?:boolean; disabled?:boolean }) {
  return <motion.button className={`clay-button ${primary?'primary':''}`} whileTap={{scale:.97,y:2}} transition={spring} disabled={disabled} onClick={onClick}>{children}</motion.button>;
}

export default function App() {
  const [mode,setMode]=useState<Mode>('home'); const [history,setHistory]=useState<HistoryItem[]>([]);
  const [device,setDevice]=useState("Vaishal's ThinkPad X270");
  useEffect(()=>{ getHistory().then(setHistory).catch(()=>{}); },[]);
  const refresh=()=>getHistory().then(setHistory).catch(()=>{});
  return <main>
    <header className="topbar"><button className="brand" onClick={()=>setMode('home')}><span className="brand-mark">⌁</span>QRBlast</button><span className="offline"><i/> Offline ready</span><button className="device" onClick={()=>{const n=prompt('Device name',device);if(n?.trim())setDevice(n.trim())}}>◉ {device}</button></header>
    <AnimatePresence mode="wait">{mode==='home'?<Home key="home" history={history} send={()=>setMode('send')} receive={()=>setMode('receive')}/>:mode==='send'?<Sender key="send" device={device} back={()=>setMode('home')} done={refresh}/>:<Receiver key="receive" back={()=>setMode('home')} done={refresh}/>}</AnimatePresence>
    <footer>MADE BY VAISHAL ANIL <span>•</span> QRBlast PWA</footer>
  </main>;
}

function Home({history,send,receive}:{history:HistoryItem[];send:()=>void;receive:()=>void}) {
  return <motion.section className="page home" initial={{opacity:0,x:18}} animate={{opacity:1,x:0}} exit={{opacity:0,x:-18}}><div className="hero"><p className="eyebrow">PRIVATE · LOCAL · OFFLINE</p><h1>Move anything.<br/><em>Just scan.</em></h1><p className="lede">Transfer files between your devices with real QR frames. No cloud, no account, no waiting.</p></div><div className="action-grid"><motion.button className="action-card send-card" whileHover={{y:-5}} whileTap={{scale:.98}} transition={spring} onClick={send}><span className="action-icon">↗</span><span><b>Send</b><small>Files, text or URLs</small></span><strong>→</strong></motion.button><motion.button className="action-card receive-card" whileHover={{y:-5}} whileTap={{scale:.98}} transition={spring} onClick={receive}><span className="action-icon">⌁</span><span><b>Receive</b><small>Scan another screen</small></span><strong>→</strong></motion.button></div><section className="history"><div className="section-head"><h2>Recent transfers</h2><span>{history.length}/20</span></div>{history.length?<div className="history-list">{history.map(item=><div className="history-row" key={item.id}><div className="file-badge">{item.fileName.split('.').pop()?.toUpperCase().slice(0,4)}</div><div><b>{item.fileName}</b><small>{bytes(item.size)} · {new Date(item.timestamp).toLocaleDateString()}</small></div><span className="verified">✓ Verified</span></div>)}</div>:<div className="empty"><span>◌</span><p>Your transfer history will appear here.</p></div>}</section></motion.section>;
}

function Sender({device,back,done}:{device:string;back:()=>void;done:()=>void}) {
  const [file,setFile]=useState<File|null>(null), [streams,setStreams]=useState(4), [advanced,setAdvanced]=useState(false), [full,setFull]=useState(false), [countdown,setCountdown]=useState<number|null>(null), [prepared,setPrepared]=useState<{meta:TransferMeta;frames:Frame[]}|null>(null), [images,setImages]=useState<string[]>([]), [running,setRunning]=useState(false), [frame,setFrame]=useState(0);
  const input=useRef<HTMLInputElement>(null), started=useRef(0);
  const choose=(f:File)=>{setFile(f);setPrepared(null);setImages([]);setFrame(0);};
  const paste=async()=>{try{const text=(await navigator.clipboard.readText()).trim();if(text)choose(new File([text],/^https?:\/\//i.test(text)?'shared-url.txt':'shared-text.txt',{type:/^https?:\/\//i.test(text)?'text/uri-list':'text/plain'}));}catch{alert('Clipboard permission was not granted.')}};
  const start=async()=>{if(!file||running||countdown!==null)return;const p=await makeTransfer(file,streams,900,device,'Laptop');setPrepared(p);setFrame(0);setCountdown(3);started.current=Date.now();};
  useEffect(()=>{if(countdown===null)return;const id=window.setInterval(()=>setCountdown(value=>{if(value===null)return null;if(value<=1){setRunning(true);return null}return value-1}),1000);return()=>clearInterval(id)},[countdown]);
  useEffect(()=>{if(!running||!prepared)return;const id=window.setInterval(()=>setFrame(x=>(x+1)%prepared.frames.length),1000/12);return()=>clearInterval(id)},[running,prepared]);
  const visible=useMemo(()=>prepared?Array.from({length:streams},(_,s)=>{const list=prepared.frames.filter(f=>f.p==='meta'||f.s===s);return list[frame%list.length]||list[0]}):[],[prepared,streams,frame]);
  useEffect(()=>{let cancelled=false;if(prepared)Promise.all(visible.map(f=>QRCode.toDataURL(frameText(f),{margin:1,errorCorrectionLevel:'M',width:520,color:{dark:'#161616',light:'#fff'}}))).then(x=>{if(!cancelled)setImages(x)});return()=>{cancelled=true}},[prepared,visible]);
  const progress=prepared?Math.min(99,Math.round(frame/Math.max(1,prepared.meta.totalChunks)*100)):0;
  return <motion.section className="page transfer-page" initial={{opacity:0,x:18}} animate={{opacity:1,x:0}} exit={{opacity:0,x:-18}}><div className="subbar"><button onClick={back} className="back">← Back</button><span className="pill">SENDER</span><span className="live-dot">● Waiting for receiver</span></div><div className="transfer-head"><div><p className="eyebrow">SEND SOMETHING</p><h1>{running?'Broadcasting':'Ready to send'}</h1><p className="muted">{running?'Receiver can scan the live QR streams now.':'Choose one file. It never leaves this device.'}</p></div>{file&&<FileSummary file={file}/>}</div>
    {!file?<div className="dropzone" onClick={()=>input.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const f=e.dataTransfer.files[0];if(f)choose(f)}}><input ref={input} type="file" hidden onChange={e=>{const f=e.target.files?.[0];if(f)choose(f)}}/><span className="upload">↑</span><b>Drop a file here</b><small>or click to browse your device</small><button className="paste-button" onClick={e=>{e.stopPropagation();paste()}}>Paste text or URL</button></div>:<div className={`qr-stage ${full?'qr-stage-fullscreen':''}`}><div className="qr-toolbar">{running&&<button className="fullscreen-button" onClick={()=>setFull(x=>!x)}>{full?'Exit fullscreen':'Fullscreen QR grid'} ⛶</button>}</div>{countdown!==null?<div className="countdown"><span>{countdown}</span><b>Get ready to scan</b><small>QR streams begin when the countdown ends</small></div>:!running?<div className="ready-copy"><span className="ready-orb">⌁</span><h2>Receiver ready?</h2><p>Position their camera, then start the transfer.</p><Button primary onClick={start}>Start transfer ↗</Button></div>:<div className={`qr-grid count-${streams}`}>{visible.map((f,i)=><div className="qr-shell" key={i}><img src={images[i]||''} alt={`QR stream ${i+1}`}/><small>STREAM {i+1} · FRAME {f.i<0?0:f.i+1}/{prepared?.meta.totalChunks}</small></div>)}</div>}</div>}
    <div className="control-panel"><div className="control-line"><div><small>QR STREAMS</small><div className="stream-picker">{[1,2,4,6,8,10].map(n=><button disabled={running||countdown!==null} className={streams===n?'selected':''} key={n} onClick={()=>setStreams(n)}>{n}</button>)}</div></div><div className="advanced-toggle"><button onClick={()=>setAdvanced(x=>!x)}>{advanced?'−':'+'} Advanced</button>{advanced&&<span>12 FPS · ECC M · 900 byte chunks</span>}</div><Button disabled={!file||running||countdown!==null} primary onClick={start}>{countdown!==null?'Starting…':running?'Transmitting…':'Start transfer'}</Button></div>{running&&<div className="metrics"><div><b>{progress}%</b><small>progress</small></div><div><b>{bytes(prepared!.meta.size)}</b><small>real file size</small></div><button onClick={()=>{setFrame(0);setCountdown(3);setRunning(false);started.current=Date.now()}}>Restart QR stream</button><button onClick={()=>{setRunning(false);done()}}>Cancel</button></div>}</div></motion.section>;
}

function FileSummary({file}:{file:File}){return <div className="file-summary"><div className="file-badge big">{file.name.split('.').pop()?.toUpperCase().slice(0,4)}</div><div><b>{file.name}</b><small>{bytes(file.size)}</small></div></div>}

function Receiver({back,done}:{back:()=>void;done:()=>void}) {
  const video=useRef<HTMLVideoElement>(null), canvas=useRef<HTMLCanvasElement>(null), raf=useRef(0), started=useRef(0), lastScan=useRef(0); const [active,setActive]=useState(false),[scanning,setScanning]=useState(false),[meta,setMeta]=useState<TransferMeta|null>(null),[frames,setFrames]=useState(new Map<number,Frame>()),[error,setError]=useState(''),[result,setResult]=useState<Blob|null>(null);
  const openCamera=async()=>{setError('');setActive(false);if(!window.isSecureContext){setError('Camera access needs HTTPS or localhost. Open the deployed HTTPS app, not a plain HTTP address.');return}if(!navigator.mediaDevices?.getUserMedia){setError('This browser does not expose camera access. Use current Safari, Chrome, Edge, or Firefox.');return}try{const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1920},height:{ideal:1080}},audio:false});const v=video.current;if(!v){stream.getTracks().forEach(t=>t.stop());return}v.srcObject=stream;v.muted=true;v.setAttribute('playsinline','true');await new Promise<void>(resolve=>{if(v.readyState>=1)resolve();else v.onloadedmetadata=()=>resolve()});await v.play();setActive(true)}catch(e){setError(e instanceof DOMException&&e.name==='NotAllowedError'?'Camera permission was denied. Allow camera access in the browser address-bar settings and tap Try camera again.':e instanceof DOMException&&e.name==='NotFoundError'?'No camera was found on this device.':`Camera could not start: ${e instanceof Error?e.message:'unknown browser error'}`)}};
  useEffect(()=>{openCamera();return()=>{(video.current?.srcObject as MediaStream|null)?.getTracks().forEach(t=>t.stop());cancelAnimationFrame(raf.current)}},[]);
  const scan=()=>{setScanning(true);started.current=Date.now();let busy=false;const detector='BarcodeDetector' in window?new (window as Window & {BarcodeDetector: new (options:{formats:string[]})=>{detect(source:CanvasImageSource):Promise<Array<{rawValue:string}>>}}).BarcodeDetector({formats:['qr_code']}):null;const consume=(text:string)=>{const f=parseFrame(text);if(!f)return;if(f.p==='meta'){try{setMeta(JSON.parse(atob(f.d)))}catch{}}else setFrames(prev=>prev.has(f.i)?prev:new Map(prev).set(f.i,f))};const tick=async()=>{const v=video.current,c=canvas.current;if(v&&c&&v.readyState>=2&&!busy&&performance.now()-lastScan.current>120){busy=true;lastScan.current=performance.now();c.width=Math.min(v.videoWidth,1600);c.height=Math.round(v.videoHeight*(c.width/v.videoWidth));const ctx=c.getContext('2d',{willReadFrequently:true})!;ctx.imageSmoothingEnabled=false;ctx.drawImage(v,0,0,c.width,c.height);if(detector){try{for(const item of await detector.detect(c))consume(item.rawValue)}catch{}}const layouts=meta?([[meta.streams,meta.streams===1?1:meta.streams<=3?1:2] as [number,number]]):([[1,1],[2,1],[3,1],[2,2],[3,2],[4,2],[5,2]] as [number,number][]);for(const [cols,rows] of layouts){for(let y=0;y<rows;y++)for(let x=0;x<cols;x++){const w=c.width/cols,h=c.height/rows,p=Math.min(w,h)*.025,d=ctx.getImageData(Math.max(0,x*w+p),Math.max(0,y*h+p),Math.max(1,w-p*2),Math.max(1,h-p*2)),qr=jsQR(d.data,d.width,d.height,{inversionAttempts:'attemptBoth'});if(qr)consume(qr.data)}}busy=false}raf.current=requestAnimationFrame(tick)};tick()};
  useEffect(()=>{if(!meta||frames.size!==meta.totalChunks)return;(async()=>{try{const buffer=reconstruct(meta,frames);if(await sha256(buffer)!==meta.hash)throw new Error('SHA-256 mismatch');setResult(new Blob([buffer],{type:meta.mime}));await saveHistory({id:meta.id,fileName:meta.fileName,size:meta.size,timestamp:Date.now(),duration:(Date.now()-started.current)/1000,device:meta.name,hash:meta.hash,mime:meta.mime});setScanning(false)}catch(e){setError(e instanceof Error?e.message:'Integrity verification failed')}})()},[meta,frames]);
  const pct=meta?Math.round(frames.size/meta.totalChunks*100):0, href=result?URL.createObjectURL(result):'';
  return <motion.section className="page transfer-page receive-page" initial={{opacity:0,x:18}} animate={{opacity:1,x:0}} exit={{opacity:0,x:-18}}><div className="subbar"><button onClick={back} className="back">← Back</button><span className="pill">RECEIVER</span><span className="live-dot">● Camera {active?'ready':'starting'}</span></div><div className="transfer-head"><div><p className="eyebrow">RECEIVE SOMETHING</p><h1>{result?'Transfer complete':scanning?'Scanning streams':'Ready to scan'}</h1><p className="muted">{result?'Integrity verified byte-for-byte.':error||'Keep the sender’s QR grid inside the camera view.'}</p></div>{meta&&<div className="file-summary"><div className="file-badge big">{meta.fileName.split('.').pop()?.toUpperCase().slice(0,4)}</div><div><b>{meta.fileName}</b><small>{bytes(meta.size)} · {pct}%</small></div></div>}</div><div className="camera-stage"><video ref={video} muted playsInline/><canvas ref={canvas} hidden/>{!active&&<div className="camera-message">⌁<b>Opening camera…</b></div>}{active&&!scanning&&!result&&<div className="camera-overlay"><span className="ready-orb">⌁</span><h2>Camera is ready</h2><p>Point it at all visible QR codes, then begin.</p><Button primary onClick={scan}>Start scanning ⌁</Button></div>}{scanning&&<div className="scan-status"><span className="scan-ring">{pct}%</span><b>{meta?`${frames.size} of ${meta.totalChunks} chunks`:'Looking for transfer…'}</b></div>}{result&&<div className="success-card"><span className="success">✓</span><h2>Transfer complete</h2><p>{meta?.fileName} · SHA-256 Verified</p><a className="clay-button primary" download={meta?.fileName} href={href}>Save file ↓</a><button onClick={done}>Done</button></div>}</div><p className="camera-note">Multi-QR detection scans a 5 × 2 grid continuously.</p></motion.section>;
}
